### ISSUE TITLE
Controller movement speed

### ISSUE THREAD

**Issue by Roland09** [thestonefox/SteamVR_Unity_Toolkit#149]
Is there a way to detect the speed / force that a controller is being moved? e. g. for a boxing game, how hard you punch?

**Comment by thestonefox** [comment]
Yeah, check out the sword example:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Sword.cs#L31

It's quite basic. But it works out the magnitude of the collision

**Comment by Roland09** [comment]
Thanks. That gives only the value at the collision. Is there a way to detect the speed / force while it's being moved? Like a "whoooooosh" sound while you move tennis racket. Or like when you move a lightsaber slow or fast.

**Comment by thestonefox** [comment]
would the velocity magnitude not tell you how fast it's moving? a higher velocity means it's moving quicker, right?

**Comment by Roland09** [comment]
Thanks for the hint. I tried that, but it didn't work. For testing purposes I attached a sphere named "GunEnd" to a gun, added a Rigidbody to the gun and set it  to kinematic = true, gravity = false and added this to the Gun.cs script:

    protected override void FixedUpdate()
    {
        base.FixedUpdate();

        GameObject gunEnd = GameObject.Find("GunEnd");
        if( gunEnd != null) { 

            float speed = gunEnd.GetComponent<Rigidbody>().velocity.magnitude;

            Debug.Log("Speed: " + speed);
        }

    }

It always gives me speed = 0 when I move the gun.

You can close this, since it isn't an issue. Though I'd be happy if you could tell me what's wrong with that approach, i. e. why the speed is 0.

**Comment by Roland09** [comment]
Thank you, I found the problem. I was using an attached child with a rigidbody. This is how it works now:

    float speed = 0;
    Vector3 lastPosition = Vector3.zero;

    protected override void FixedUpdate()
    {
        base.FixedUpdate();

        speed = (((transform.position - lastPosition).magnitude) / Time.deltaTime);
        lastPosition = transform.position;
    }

**Comment by thestonefox** [comment]
Ah cool. Yeah I guess velocity won't work on an object you're moving with the controller because the object itself has no velocity because it's just tracking the controller. But using the magnitude of the positions would give a close enough approximation :)

Do you need to do it in the FixedUpdate? Would Update be ok?

I know FixedUpdate will be a lot more precise but is the precision worth the performance hit?

**Comment by Roland09** [comment]
I only put it in FixedUpdate because I read so. It's not necessary to have it there. If that's a performance problem, I'll put it into Update, thanks for the hint.

**Comment by thestonefox** [comment]
It's just that FixedUpdate is run tonnes of times per frame, meaning your speed calculation is run a load more times, the Update is only run once per frame.

FixedUpdate is really useful when dealing with physics calculations because it's really precise and you get a fewer glitches with collisions, etc.

But I feel for getting an approximate speed, you could get away with using just Update. Unless you need it to be really precise.

**Comment by Roland09** [comment]
Good to know. It's currently just for gaming atmosphere, i. e. playing a
sound when the user makes a fast gesture.
