### ISSUE TITLE
Controllers are only recognised as a pair?

### ISSUE THREAD

**Issue by paulcanning** [thestonefox/SteamVR_Unity_Toolkit#175]
(Not sure if this is Toolkit related, but I'm not sure where to ask)

When I start my scene, with the CameraRig etc in place, one controller is always shown on the floor, despite them both being on my desk.

Then, one controller will not work until both controllers are detected by the lighthouses?

Anyone else experiencing this?

**Comment by xEvoGx** [comment]
Yup rather consistently and for the most part only in Unity (I'm certain it's happened initially in a game but always corrected itself...I think)

However in Unity, this phenomenon is rather consistent. I'll get anything from the controller not appearing, to being _elsewhere_ to being misaligned after it _corrects_ itself and appears in my hand. There was a point where the controller mesh was tracking but not in the correct place in VR.

**Comment by paulcanning** [comment]
Phew, glad to know it's not just me!

Hoping that someone here can figure this out!

**Comment by thestonefox** [comment]
I've been getting the same thing recently. I'm pretty sure it was working where you could turn on either controller and it would find them after you launched your game in unity.

I remember when I re-wrote the controller detection code specifically checking for this behaviour.

So I'm not sure if something has changed since with SteamVR. I will look into this code and see if it's something going wrong in here, but I don't think anything has changed in that department.

**Comment by paulcanning** [comment]
That'd be great, thank you.

I'll double check to see if the issue happens in a build.

**Comment by paulcanning** [comment]
Closed? Did you find anything?

**Comment by thestonefox** [comment]
It's an issue with SteamVR and/or unity so not much I can do about it unfortunately :(

**Comment by paulcanning** [comment]
Ah, never mind then!
