### ISSUE TITLE
Teleport doesn't work on Builds

### ISSUE THREAD

**Issue by Nic-vanDessel** [thestonefox/SteamVR_Unity_Toolkit#181]
Just went to build my project and my teleport doesn't work. Tried it in another project that I use for testing and it dint work there either. Also tried in a new project using one of your example scenes and that also didn't work.

**Comment by thestonefox** [comment]
Check out the FAQ in the readme:

Pointer beams/teleporting no longer works after a project build and running from that build:View answer video on Youtube

**Comment by Nic-vanDessel** [comment]
Perfect, sorry for opening an issue!

**Comment by xEvoGx** [comment]
Not to ask a stupid question, but because this is one of those issues that's not terribly obvious (I've never had to do anything in my Graphics Settings), why not include a generic GO that has this shader applied or place the shader in _Assets/Resources_?

I understand that placing assets in another folder outside of **/SteamVR_Unity_Toolkit** kind of messes up keeping things tidy in a single folder, so perhaps having a GO in the scene that isn't activated or really small/far away/under the world is reasonable enough to avoid having this question emerge again.

Cheers

**Comment by thestonefox** [comment]
That won't solve the issue for people who start fresh and don't include the game object

**Comment by xEvoGx** [comment]
Well you are supplying a Prefab for the CameraRig to which you can attach this GO...

...but yea otherwise you're right, didn't think about that! :)

**Comment by thestonefox** [comment]
tis true, but I'm looking to deprecate the CameraRig prefab as soon as we get to the bottom of the Valve prefab differences.

**Comment by xEvoGx** [comment]
Yea completely makes sense...ignore me! Carry on good sir!!
