### ISSUE TITLE
Proxy 'Hand' to Aid in Object Alignment

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#194]
Since I've only been playing around in VR with the _default_ Vive controllers, in now wanting to pursue holding objects that need a very specific alignment to the hand (i.e. holding a weapon), I realize it's largely trial and error to find what that _natural_ placement is without actual Vive controller **models** in Unity.

So either I'm going about this the wrong way, unbeknownst to me, or maybe it isn't a terrible idea of have a basic _placement object_ that devs can align objects to. This could be a proxy of the Vive controllers, or even a basic 'hand' shape.

Thoughts?

**Comment by thestonefox** [comment]
do you mean a physical object that looks like a controller whilst your in edit mode?

Or do you mean like an empty game object transform that you use to align the snap position?

If it's the latter, then we have the new Handle_Snap feature which does this

**Comment by xEvoGx** [comment]
Yea this is about editing, attempting to align objects with the controller so they feel like they're being held _correctly_ in a hand. Again think of holding a virtual gun. You want it to mirror as closely as possible to how it would feel to actually hold a real weapon.

Just a proxy object that sure, could be the Vive controller, or even just a hand that roughly approximates your real hand when holding the controller, so it's easy to align objects that need to be held a specific way.

**Comment by thestonefox** [comment]
You can use the "Handle Snap" mode and for the snap point handle (the empty game object used for position and rotation) if you add in a cube, instead of an empty game object and set it's scale to like [0.05, 0.05, 0.2] then that cube will give a decent visual reference to the basic shape of the controller. If you position that then it will be where the controller will grab.

You can just disable the mesh renderer (untick the checkbox in the inspector) to make sure the snap point doesn't show in the game.

It may be worth in the future having the Interactable Object script render an editor gizmo to show this without needing the additional mesh renderer, but it's probably not something that will get done soonish.

**Comment by xEvoGx** [comment]
Actually yea I realized what I was looking for was the Vive controller model in:

**\steamapps\common\SteamVR\resources\rendermodels\vr_controller_vive_1_5**

...which of course I'm going to assume has the local axis the controllers use in VR. There I can best align objects prior to export to Unity.

Anyway thanks again Stone

-Steven
