### ISSUE TITLE
Possible to add a Dash "teleport" script to the toolkit?

### ISSUE THREAD

**Issue by dre4mer12345** [thestonefox/SteamVR_Unity_Toolkit#203]
The toolkit is already got all kinds of cool stuff, I've been working on a simple game where you can dash in any direction you are facing in 3D Space, so not just along the ground plane. Both would of course be useful in different cases though.

Jan posted a start on slack it looks like, but it seems to mess up the other VRTK scripts at the moment.

Thanks again keep up the good work!

-Ethan

**Comment by thestonefox** [comment]
I've looked at the script from Jan, seems like a good start, I've left a few pointers on how to improve it

What other scripts does it mess up for you?

**Comment by baemoth** [comment]
I wanted to propose something just like this. Any chance I can have a look at the script?

**Comment by thestonefox** [comment]
I believe he posted it on the slack channel, worth checking in there

**Comment by mimminito** [comment]
So how would people like this to work? Would you want this to use the pointer still? So wherever the pointer is aiming, dash in that direction? Or not use a pointer, and wherever the user is looking, dash in that direction?

Seems pretty easy to implement, if people could list what they are after I might give it a go.

**Comment by xEvoGx** [comment]
Both? I really like the idea of a **Gaze Dash** (_public bool gazeDash = true_)...

...look, squeeze grip, swoosh! That would feel efficient and remove one extra step (i.e. pointing a controller).

**Comment by dre4mer12345** [comment]
In my usage it would be where ever you are looking you dash in that direction when the input is squeezed. And maybe a setting to change if it's along the ground plane or just forward the direction you are looking (aka) into space if that was possible. 

To be able to change the "intensity" of the dash. via speed and distance could be really useful too, though I'd hope those would be modifiable easily enough in the code?

That said I don't look a gift feature in the mouth :) Any dash functionality would be great!

**Comment by baemoth** [comment]
can that be made to work on different inputs for direction? like areas on the trackpad instead of look direction? it would make it more flexible.

**Comment by mbbmbbmm** [comment]
Hi all! I expanded on my original script a bit and will make a pull request tomorrow. It's my first time forking, quite the adventure. I'll add some documentation and a simple scene.

**Comment by fyrefli** [comment]
It would also be great if the teleport didn't have to hit an object, but would dash you the length of your controller pointer, so you could dash into the "empty air" . Either that, dash a set distance in the direction you are looking.

**Comment by mbbmbbmm** [comment]
Hmm interesting idea, but wouldn't that be an extension of the whole teleport system? The dash is just the style of traveling.
Dashing a set distance doesn't appeal that much to me personally, it would be hard to set a good distance and take away a lot of control from the user.

**Comment by fyrefli** [comment]
Yes, that's true, I did make a different topic because of that, but also commented here because my use would be best with the dash feature. Sorry if it clogged up this discussion!

I suppose I am thinking it would still hit objects if the object is within your teleport pointer range, but it could also go into the empty air. The idea being you are not limited to teleporting to a ground plane or object, but have the capability to travel in open space (ie, if you were in water you could "swim" anywhere, not just to an object). The trackpad walk feature could do this, but the dash creates less motion sickness than actually slowly walking forward.

**Comment by mbbmbbmm** [comment]
Yes I see, no worries!
Ah in this case if you're going for a swimming feeling I would ditch the dashing through objects (and maybe the pointer) and just dash that short set distance or - if it happens to be closer - up to the first object the CapsuleCast returns. Unfortunately the CapsuleCast isn't as robust as I'd like it to be right now. It seems that it works maybe 80% of the time. I'm hoping that someone can find out what I did wrong or how to improve it.

**Comment by fyrefli** [comment]
Yeah, that sounds exactly like what I was wanting to do.

**Comment by loumanv** [comment]
Hi guys, has there been any progress on this? What's the latest implementation? I would like to take a look as well and try to help out with this. Thanks a lot for all the great work on this!

**Comment by mbbmbbmm** [comment]
I've had little time but I'm planning to finish a version by tomorrow evening. You are very welcome to have a look, test and help out then! cheers!

**Comment by dre4mer12345** [comment]
Hey guys, Thanks for working on this!

I wanted to add a couple thoughts on this. We've been trying to use the dash script but started having alot of issues with non-collision on overhanging walls (if your feet can get closer than your head to a wall) because the player presence collider won't stop you from getting too close to an object when using dash. We messed with alot of things trying to add colliders or expand the size of player presence but basically, using dash you can get through any walls unless they are vertical or farther angled away.

So we started instead playing with a strong impulse force applied to the player in the orientation of your controller. Which gives you the same burst of speed and collisions work that way. Now someone with a better understanding of the player presence and how the dash script works could probably figure out how to get collisions to perform using it. But at the moment this is all we can get to work in our usage.

**Comment by mbbmbbmm** [comment]
I pushed a new version to my fork. The script also contains a naive starting point for the dash-to-object-functionality, but it is commented out because it didn't work out too well unfortunately. I think it would be good if someone with a good understanding of vector math could take it further.
I am also sure the CapsuleCast could be improved by such a person...

@dre4mer12345: I used the lerp because the time can be set exactly in order to avoid sim sickness. I'm not sure if that is possible with a force based approach. But if it does it might be a good thing to use for the dash-to-object and for any player presence based methods of course. If you just want to avoid getting to near toward some of the objects theres always the possibility to add invisible colliders with a don't-teleport-tag/class on them (there's an example somewhere in the project).

@loumanv: please test away :)

@thestonefox: I hope I did everything right with git and the commit this time ;)

**Comment by dre4mer12345** [comment]
@mbbmbbmm Yeah lerp definitely would be a better way to handle it. We were able to get a decent dash feeling by cranking up the impulse amount alot and putting up the drag and the mass for a fast slow down and speed up. I'm super prone to sim sickness myself and it is working fine from that perspective. But as you can imagine it's a bit tricky to get the distance and speed precise without alot of testing values. I'll have to look a bit into don't teleport-tag. thanks.
