### ISSUE TITLE
Blocking using unless grabbed?

### ISSUE THREAD

**Issue by CuriousConstruction** [thestonefox/SteamVR_Unity_Toolkit#234]
Fairly new but I'm not seeing a built in bool or something similar to block an item from being 'used' without it being in a grabbed state. 

For example in the examples with guns you can fire them without having to pick them up.  While somewhat realistic I suppose it's a little weird until you add the correct force to such items so that they go flying in the 'for every action there is an equal and opposite reaction' direction.   A hand grenade to use another violent example would be almost impossible to pull the pin from IRL without it being grabbed. 

Just curious if such a flag might be on the roadmap to be implemented in the base code?  With such active development I don't necessarily want to start forking it for personal use and then have to go back and merge awesome new features back into mine.

**Comment by mimminito** [comment]
You could for now just create your own script to handle this. Register against the events on the object to check for when its grabbed/released, and set the using flag based on whether its picked up or not. Pretty simple script.

**Comment by thestonefox** [comment]
I would agree with @mimminito on this one. You'd check the grabbed status in your script that inherits the interactable object. It's more sensible to do it this way as you'd only ever have this issue if you were extending the core functionality anyway.

Otherwise we could end up having an option to support everything :)
