### ISSUE TITLE
[Suggestion] Teleport - Negation of the tag-check proposal

### ISSUE THREAD

**Issue by smygarn** [thestonefox/SteamVR_Unity_Toolkit#266]
I've tested out the height adjust teleport this night and found that I jumped up on all kinds of objects when I was over them! 

I then found out the solution. Tag or put ExcludeTeleport to ALL your objects with a specific tag to filter them out. 

It may work out well in the examples, but in most real usecases I think it's the opposite here. There are probably far less objects that you should be able to walk on.

Easy fix is to rename invalidTargetWithTagOrClass to validTargetWithTagOrClass and negate the validation check. 

Then you can just mark out your groundlevel with this tag!

**Comment by thestonefox** [comment]
This question comes up a lot, but the solution you've provided isn't workable.

Firstly, if you have an opt in method where you have to tag items to teleport to, then many people will just want it the other way where they want to have it only exclude locations, they will also say "this is the most obvious use case".

Secondly, people will be adding in objects and wondering why the teleport is broken because they won't realise they have to then tag all the items before they can teleport on to them, meaning more questions will come flooding in, and no matter how much documentation there is or videos on the subject, people will always ask first then rtfm later. This means more questions is a drain on time.

What works for one person doesn't work for someone else, but the current implementation is easier for people to get their head around because teleporting naturally works until you want to prevent it from working and that's the point when you apply exclude logic.
