### ISSUE TITLE
Ignoring other Rigidbody collisions on a grabbed object

### ISSUE THREAD

**Issue by Cubiverse** [thestonefox/SteamVR_Unity_Toolkit#269]
I am having issues with picking up stacks of VRTK_InteractableObject - the grab causes they to explode everywhere and I was looking for a way to disable the rigidbody on the grabbed object.

I have a DoObjectGrab() similar to the BowAim class and tried setting isKinematic = true, PauseCollisions(),etc.. but the RigidBody still hits everything around it.

How is this accomplished?

I believe the BowAim uses a system of manually setting rotation and position (though I've not had time yet to get into the code) - is this how it would normally be done?

**Comment by thestonefox** [comment]
If you stack a cube on top of another cube, then grab the bottom cube with a simple snap mode meaning the cube centre snaps to the tip of the controller, then the change in position of the bottom cube will cause a force to be applied to anything on top of it, which is why things shoot everywhere.

You could try ticking the precision snap, so you pick up at the point of grabbing the bottom item, or you could try a different grab mechanic like track_object and see if that works any better for your needs.

**Comment by thestonefox** [comment]
I tried this out last night, using precision snap works as it doesn't jolt the bottom item to your controller central point (causing the force to apply).
