### ISSUE TITLE
Teleport freezes when holding object / Teleporting thru objects

### ISSUE THREAD

**Issue by swlu** [thestonefox/SteamVR_Unity_Toolkit#318]
This is an amazing toolkit!  But have encountered a few teleporting bugs.  Wondering if anyone can help.

The first is if grabbing or holding an object, teleport usually (not all the time) freezes up in that hand and teleports only along the y-axis.  

And the second is that even if I tag an item with 'noteleport' and it appears red, if I teleport to it's edge I can easily teleport thru the object.  It also clips when teleporting to the edge of a mesh (eg. a wall).  

Any help would be appreciated, thanks!!

**Comment by thestonefox** [comment]
Are you able to provide a video demonstrating the issue you're having as I cannot seem to replicate it.

**Comment by swlu** [comment]
https://www.dropbox.com/s/xf1m4jb7qm5e9zw/swlu%20teleport%20issues%207%2030%2016.mp4?dl=1

Here's a video showing and explaining the two issues.  BTW, I'm a complete novice so I could very well be doing things completely wrong, but any help would be great.

Thanks Mr. Fox!!

**Comment by thestonefox** [comment]
So it looks as if the first issue may be being caused by the object you're holding is getting hit by the teleport raycast and therefore your teleport destination is just right in front of you (i.e. at the object you're holding).

I'll look into that and see if i can replicate and fix it.

The second issue where you're teleporting through walls is because when you put your hand through the wall, the teleport beam is actually already passed through the collider and it's on the other side of the collider. It's a common issue in VR games where you can cheat this way (you can do it in Budget Cuts for example).

There are ways of mitigating the issue (such as thick walls, etc) but I'm also trying to work up some other clever ideas of how to prevent it.

**Comment by swlu** [comment]
Awesome, thx for checking it out and the quick response!

**Comment by thestonefox** [comment]
Ok so the issue is the offset of your object is causing the pointer raycast to hit your object first.

The quickest solution is to set your object's layer to "Ignore Raycast" then the teleport beam will never hit it and pass right through it.

There may be a code level solution I can implement to automate this, but it requires some thought as it could mess up custom layers others may be using.

But for your needs just set the Object to the "Ignore Raycast" layer and you'll be fine :)

**Comment by swlu** [comment]
Awesome, thx so much for the solution!!
