### ISSUE TITLE
DeviceFinder Helper Photon Networking  Instantiate issues

### ISSUE THREAD

**Issue by Dirly** [thestonefox/SteamVR_Unity_Toolkit#331]
So with a multiplayer game I was having issues with how DeviceFinder leverages FindObjectOfType  especially using the VRTK_PlayerPresence script.  It would grab all disabled components as well.  Player 2's presences was always thrown out of wack.  It was locating 2 instances of the headsets, and not sure how to adjust the floor for it.  

My quick fix was to change in VRTK _PlayerPresences to GetComponentInChildren on line 31, instead of leverage DeviceFinder.   

I would suggest moving the DeviceFinder to leverage GetComponentInChildren, instead of FindObjectOfType which is scene wide.

**Comment by thestonefox** [comment]
Ok thanks, I'll look into how this is working.

Perhaps it should only find enabled instances.

**Comment by Dirly** [comment]
@thestonefox yeah I think that would work.  Though I didn't go crazy into reviewing devicefinder.   It would be nice if you could pass the parent somehow that way you know its only looking in that instance of the camera rig.

**Comment by thacio** [comment]
Non-related to the toolkit directly, but might be good to exchange ideas about design. (I just started working with photon two weeks ago, so I trying to learn more)

Wouldn't it be better to destroy every VRTK and SteamVR components for non-local player? (instead of disabling them)
I think it would avoid this type of problem. Then all non-local player variables would be synchronized using photon view.

If needed to find who owns the script, the workaround I'm using checking the owner of the PhotonView on the [CameraRig], something like
myScript.transform.root.GetComponent<PhotonView>().IsMine or .ownerID.

**Comment by Dirly** [comment]
@thacio you could do that.   I was just trying to leverage one asset,  so it enables disables what it doesn't need.   It starts off as all items are disabled,   I'm guessing the way I did it wasn't the best,  this was my first attempt at photon and VR as well.
