### ISSUE TITLE
SteamVR 1.0.9 has been released, ensure toolkit works with new version

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#36]

**Comment by thestonefox** [comment]
A straight delete and re-import seems to work ok so far.

The SteamVR_TrackedObject script needs updating to add in the code from commit: 7da9e511f2613d85948f95ecd1dff652d0896e3c

**Comment by EctoArckanox** [comment]
Hi !

First thanks for all your nice examples, they are really useful.
I started playing with unity and VR yesterday evening.

When I tried using SteamVR_Unity_Toolkit I first got really confused as nothing I tried seemed to work because of today's Steam VR update. (c# errors in scripts)

While I managed to try examples by reloading SteamVR_Unity_Toolkit without updating, the "straight delete and re-import" gives me more trouble than it should.
First having SteamVR sitting in "\Assets\SteamVR_Unity_Toolkit\Required Includes"
instead of "\Assets" like it is by default is a bit confusing to update for newbie.
Second, when I tried doing it, I got an error about not being able to copy an openvr dll or something.

Thank you a lot for everything you've done so far, those examples are the best I've tried,
but as this seem to aimed at beginners, I thing it would be nice to keep it simpler, by having the SteamVR folder at it's default place for example.
Also, you seem to use an older version of unity? the latest, 5.3.4f1 updates the project when importing the first time.

**Comment by thestonefox** [comment]
@EctoArckanox 

Yeah this toolkit modifies one of the scripts in the SteamVR plugin, so you can't use the actual plugin, just the one included in this repo, which is rubbish, but was necessary at the start as Valve didn't seem like they were maintaining their repo, hopefully now they are active on it, I can look to separate the dependency out of this repo all together (this is what I want).

Once (if) it has been separated out then it would just default to whatever location you had imported it to.

I'm using 5.3.4f1 as well

**Comment by EctoArckanox** [comment]
Awesome, thanks again for you work :)
 :+1: 

Here is the message I get when I open the project for the first time after downloading and extracting the zip from github :

your project was last opened with a different setup of Unity.
C:/Users/Public/Documents/Unity Projects/SteamVR_Unity_Toolkit-master
The saved project (before 5.0) does not match the launched editor (5.3.4f1)
This may require re-import. Please be aware that opening in an older version is unsupported.
Note that if a build target installation is missing, this may also cause a re-import.

**Comment by thestonefox** [comment]
@EctoArckanox 
Don't worry about that message, just continue past it, everything should work

**Comment by EctoArckanox** [comment]
Thanks. It's indeed not an issue. Just weird.
Do you plan to update SteamVR_Unity_Toolkit to SteamVR 1.0.9 soon ?

**Comment by thestonefox** [comment]
I was planning on doing the update today, if time allows for it! :)

**Comment by thestonefox** [comment]
Looks as if Valve are as lazy as always with their code checking :(

Trying to generate a build from 1.0.9 creates a compile error in their SteamVR_LoadLevel file

Will I ever be able to escape this hard dependency :(

**Comment by thestonefox** [comment]
I'm not doing this upgrade until Valve can get their side stable

This is the outstanding issue: https://github.com/ValveSoftware/openvr/issues/101

**Comment by thestonefox** [comment]
I may actually merge the upgrade commit because it's nothing to do with upgrading really, it's just removing the dependency. Then any issues with the SteamVR plugin are no longer my concern :p

**Comment by EctoArckanox** [comment]
Dammit valve !

**Comment by thestonefox** [comment]
I've removed the included Required Includes now so the plugin is separated from this toolkit repo

https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/0ef9d60a1a6ce96202cbf9fa364c5d1395fcf922

This can be closed as the external dependency is not my issue :P
