### ISSUE TITLE
RigidBody not reenabled after drop

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#405]
When grabbing and holding an object and then moving it against an obstacle it will detach the joint. Still holding the grab button will now not have any effect anymore on obstacles though. One has to release and regrab to have the rigidbody working again. 

When the object is detached this should be detected and handled as if it was dropped manually.

**Comment by thestonefox** [comment]
Is that your grab issue you've been experiencing? Hopefully so, this seems reproducible and fixable :)

**Comment by 10FingerArmy** [comment]
unfortunately not, it's different but still very confusing ;-)

**Comment by thestonefox** [comment]
dang it :(

**Comment by thestonefox** [comment]
Thinking about it, is this an actual bug?

If you're holding something and you bang into something and drop the item, you should have to release your grip to pick it back up again, no?

Holding the grip down after you've dropped something won't help because the event the grip is listening for is the "Grab Alias" being pressed.

What I'm seeing here is if you bang it into something it is treated as if you've dropped it manually (i.e. you have to press grip again to pick it up)

i.e. if you hold something in real life and it falls out of your gripped hand, you have to open your hand again to grip again.

**Comment by 10FingerArmy** [comment]
yes for picking it back up that definitely should be the case to release and regrab, but the rigidbody controller should be back enabled after a detach so that I can still move other objects by touching them

**Comment by thestonefox** [comment]
Are you saying the rigidbody on the controller isn't being re-enabled?

I'm trying this in the 005 Basic Object grabbing scene, i don't seem to see any problems? Can you give me a simple dummy guide on how to recreate the issue?

**Comment by thestonefox** [comment]
Note: If you auto drop an object and you're still holding the grab alias down and Create Rigidbody When Not Touching is selected, then after the auto drop the rigidbody should be on because the grip is still being held down but you're not touching anything.
