### ISSUE TITLE
Can't get trigger pressed event

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#442]
I copied almost the example 14 and the gun object, but the method StartUSing(...) is never called ?

```
public class GunDouble : VRTK_InteractableObject {

	public GameObject bulletObj;
	private float bulletSpeed = 1000f;
	private float bulletLife = 5f;
	private GameObject bullet; 
 

	public override void StartUsing(GameObject usingObject)
	{
		base.StartUsing(usingObject);
		Debug.logger.Log ("Firing");
		FireBullet();
	}

	protected override void Start()
	{
		base.Start();        
	}

	private void FireBullet()
	{
		bullet = transform.Find("fire1").gameObject;
		GameObject bulletClone = Instantiate(bulletObj, bullet.transform.position, bullet.transform.rotation) as GameObject;
		bulletClone.SetActive(true);
		Rigidbody rb = bulletClone.GetComponent<Rigidbody>();
		rb.AddForce(bullet.transform.forward * bulletSpeed);
		Destroy(bulletClone, bulletLife);
	}
	  
}
```
Can't we have a simple Update() function and detect if trigger is pressed checking a boolean ?

**Comment by thestonefox** [comment]
You can if you want, the ControllerEvents script sets a public boolean on whether the trigger is pressed or not:

https://steamvr-unity-toolkit.readme.io/docs/controllerevents#section-class-variables

However, StartUsing does work, because the example script uses it and that works, so the issue must be somewhere else in your configuration.
