### ISSUE TITLE
[Inspiration] NewtonVR

### ISSUE THREAD

**Issue by bcoyle** [thestonefox/SteamVR_Unity_Toolkit#46]
https://github.com/TomorrowTodayLabs/NewtonVR

Someone shared this with me on Reddit, thought I'd pass it along for others to check out. I'm not sure if there's anything in there that might inspire some new features to incorporate into the Toolkit.

**Comment by thestonefox** [comment]
I'm going to check it out now. I'd heard it mentioned but wasn't sure what it was. Good to have more of this stuff on github, all helps VR development move forward!

**Comment by thestonefox** [comment]
They have some really cool widgets on there, I like their text selection wheel, that's a cool idea. So are the sliders and the number dial.

**Comment by blakeman399** [comment]
I actually have been using both this repo and NewtonVR. It would be amazing to see a hybrid of these two for sure!

**Comment by thestonefox** [comment]
Yeah they have some really nice widgets. It's a shame we're doing things a different way. Be awesome if their widgets worked here, but then that goes against what they're doing. And if I recreate their widgets then it's going against the generic nature of this repo.

I can probably recreate some of their stuff using the standard scripts.

**Comment by pixelvspixel** [comment]
One of the nice things about Newton is that the physics don't freak out if you pass the controller into a collision while influencing a physics object.  I realize this is because they are blending between the two controller models in a completely different way.

**Comment by thestonefox** [comment]
@pixelvspixel The way they do object grabbing looks different, they don't attach objects to the controller with a fixed joint. They constantly update the object's position and rotation to match the controller's, which has some other adverse side effects as you can see with the gun in their scene where it's constantly playing catch up with the controller's position/rotation and feels a bit laggy.

Pros and cons to both ways, physics engines don't have enough computer power behind them yet to act as expected, hopefully the next gen of graphics cards will solve that.

**Comment by thestonefox** [comment]
I've implemented the fix for preventing objects from going through other objects and acting crazy.

Now what happens is if you try and do that the object just drops. I think it's a bit more natural than having the item stop where it collided then snap to the controller after. Horses for courses I guess, but at least it doesn't make object go all jittery anymore! :)

**Comment by bcoyle** [comment]
another interesting teleportation mechanic on github, https://github.com/Flafla2/Vive-Teleporter

**Comment by thestonefox** [comment]
@bcoyle yeah saw it, I dropped the dev a note to see if he wanted to implement it into this toolkit too.

He said he may if he has time, I've asked him if he minds me implementing it on his behalf.

**Comment by bcoyle** [comment]
@thestonefox Cool! Yeah I love the idea of getting as many of these mechanics together as possible. I love the work you're doing and having this toolkit for people to experiment with all the options available for themselves.

**Comment by thestonefox** [comment]
@bcoyle yeah I love seeing other people's ideas too for VR. I really like that teleport script, I love the way the curve is drawn and animated like in The Lab.

I want to try and build up a good collection of scripts and ideas for people to just pick up, use, play with and extend into their own games.

Even things that I think may not work too well (like the touchpad walking thing I'm working on) it's just useful to have a collection of things for people to get inspired by.

**Comment by 10FingerArmy** [comment]
I have taken a longer look at NewtonVR now. I love how the button, switch and the drawer just feel right. Also the collision of the controller is much better than with the sphere collider here.

While it has some really nice ideas the development is not at a level that can or should be readily used though. Many things happen in Update methods instead of being event driven. Also not using a fixed joint when holding e.g. a pistol feels just wrong in my opinion as objects now are following very slowly and unnaturally pulling me out of immersion. Suddenly this is not my hand anymore but a controller to which an object is following. I still wish we could unite the projects into one and get more people to concentrate on contributing here.

What I really suggest doing is gradually building up a library of interaction controls. I will start with a button and try to contribute.

**Comment by thestonefox** [comment]
Yeah, their object control is nice, but they have different scripts for different types of objects, like the drawer requires a specific script, then they have rotators and other types of hinge scripts.

I wanted to see what could be achieved with a generic script.

Their demo scene has some really nice widgets, but their grab tracking does suck (it can be replicated by setting the grab mechanic to Tracking Object in this repo)

Be nice to have a collection of widgets like they offer but with minimal amount of custom scripts required.

**Comment by thestonefox** [comment]
Any objections to closing this thread and moving it to the sub reddit?

**Comment by thestonefox** [comment]
Moving this discussion to here:
https://www.reddit.com/r/SteamVRUnityToolkit/comments/4n4425/newtonvr_inspiration_for_ideas/
