### ISSUE TITLE
Height Adjust Teleport triggers drop to floor excessively

### ISSUE THREAD

**Issue by sidcitris** [thestonefox/SteamVR_Unity_Toolkit#489]
While testing a script in the climbing example, I had an issue where I was being teleported to the floor instantly while climbing. I traced the issue back to an OnTeleporting callback getting triggered in VRTK_HeightAdjustTeleport.cs. It appears the floorY variable can vary slightly due to noise in either the Raycast or the eyeCamara tracking position. 

The comparison on line 155 needs a small tolerance in order to potentially avoid this issue. I was regularly seeing a previousFloorY = 0.0 and an extremely small floorY ~= 1.0E-7. This means a calculated height difference of a micrometer was enough to trigger a teleport.
https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/VRTK/Scripts/VRTK_HeightAdjustTeleport.cs#L155

```
                Ray ray = new Ray(eyeCamera.transform.position, -transform.up);
                RaycastHit rayCollidedWith;
                bool rayHit = Physics.Raycast(ray, out rayCollidedWith);
                float floorY = eyeCamera.transform.position.y - rayCollidedWith.distance;

                if (rayHit && ValidLocation(rayCollidedWith.transform, rayCollidedWith.point) && !FloorIsGrabbedObject(rayCollidedWith))
                {
                    var floorDelta = currentRayDownY - floorY;
                    currentFloor = rayCollidedWith.transform.gameObject;
                    currentRayDownY = floorY;

                    float fallDistance = transform.position.y - floorY;
                    bool shouldDoGravityFall = useGravityFall && (playerPresence.IsFalling() || fallDistance > gravityFallHeight);

                    if (withBlink && !shouldDoGravityFall && (floorDelta > blinkYThreshold || floorDelta < -blinkYThreshold))
                    {
                        Blink(blinkTransitionSpeed);
                    }

                    if (floorY != previousFloorY) // Could be replaced with (Mathf.Abs(floorY - previousFloorY) < minHeightThreshold)
                    {
                        if (shouldDoGravityFall)
                        {
                            playerPresence.StartPhysicsFall(Vector3.zero);
                        }
                        else // teleport fall
                        {
                            Vector3 newPosition = new Vector3(transform.position.x, floorY, transform.position.z);
                            var teleportArgs = new DestinationMarkerEventArgs
                            {
                                destinationPosition = newPosition,
                                distance = rayCollidedWith.distance,
                                enableTeleport = true,
                                target = currentFloor.transform
                            };
                            OnTeleporting(gameObject, teleportArgs);
                            SetNewPosition(newPosition, currentFloor.transform);
                            OnTeleported(gameObject, teleportArgs);
                        }
                    }
                }
```

**Comment by thestonefox** [comment]
i think a tolerance value may be a good idea here. I'll look at adding a param for it.

**Comment by thestonefox** [comment]
Check out this PR and see if it fixes your issue:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/507

**Comment by sidcitris** [comment]
Looks good. I had worked around it, but I figured it would be a slight performance improvement to avoid unnecessary callback triggers. Thanks

**Comment by thestonefox** [comment]
I'm not happy with the current PR, i think it can be refactored to make it better. At the moment it looks like things are happening (e.g. blink) when they don't need to be.

I'm going to have another go at cleaning it up

**Comment by thestonefox** [comment]
I've updated the PR with a different refactored version where stuff shouldn't get unnecessarily called

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/507/commits/5e47d291f42b634691b0547be01236cb17ce1666

check it out and see if this works for you

**Comment by ridoutb** [comment]
I found an issue with the collider that is a child of the Camera Rig. The collider is too big. The raycast is done from the center of the collider. You can step over a ledge, and raycast down to the ground. That triggers  a fall, but the back of the collider is still on the original ledge. You "fall" and land on the surface you fell from, and then you are stuck on that Y-plane because it things you landed on that new floor, even though you never left the original floor.

**Comment by thestonefox** [comment]
@ridoutb can you provide a video showing the issue?

**Comment by ridoutb** [comment]
Sure.

**Comment by ridoutb** [comment]
Having spent some time on this, I have some more thoughts. Shifting the raycast behind the player allows you to properly fall off ledges, but since it is no longer centered, tilting your head up or down actually adjusts the headsets Y-position in space (which is not a good feeling) This makes sense since a raycast behind you would be shorter when you look up and longer when you look down. I've seen other systems use multiple raycasts at the extents of the collider. You would have to reconcile them all, and only fall once they had all left the current floor. You could still get the y_position from a center raycast, but base falling off the ones at the extents of the collider.

**Comment by thestonefox** [comment]
@ridoutb what are the settings you're using the the height adjust teleport? also do you have the player presence on the camera rig as well?

**Comment by ridoutb** [comment]
@thestonefox Mostly default settings on the Height Adjust Teleport. I've got the Gravity Fall Height set low because I want it to kick in quickly. It's 0.25 currently.  I believe PlayerClimb adds PlayerPresence onto the main/top-level CameraRig. I think I copied the component that got added while it was running and then pasted it onto the same CameraRig when my project was not running. Other than that, no changes I'm aware of.

**Comment by ridoutb** [comment]
codebison suggested using a BoxCast. I think that would solve this issue since then the raycast and the collider could have the same bounds.

**Comment by thestonefox** [comment]
@ridoutb let's start an new issue with your finding as it's not related to this issue.

**Comment by thestonefox** [comment]
Link to other issue : https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/529
