### ISSUE TITLE
Rotating Camera rig breaks xy controller teleport

### ISSUE THREAD

**Issue by B33T** [thestonefox/SteamVR_Unity_Toolkit#52]
Hello! if i rotate the camerarig then teleport on the controllers / bezier pointer go all of the place. for instance if i rotate it 180 the bezier comes from the bottom of the controller.

**Comment by thestonefox** [comment]
This is expected. The camera rig should stay at the right orientation. See this FAQ:

https://youtu.be/WptCSrSBOZo

**Comment by phr00t** [comment]
This would conflict with Touch support, right? Oculus is targeting a forward-facing setup, so the only way a player would be able to work behind them is if the camera rig was turned around (so the player still can face towards cameras but be backwards in the virtual world). SteamVR's goal isn't just Vive support, so I wouldn't want to see fundamentally implemented choices limit what hardware can be supported.

**Comment by thestonefox** [comment]
I'm not sure. I only have a Vive so it's really difficult for me to build for anything other than that at the moment.

I'd like to support SteamVR they way they intend for it to work, but without the hardware that may be very difficult.

**Comment by phr00t** [comment]
I don't have Touch either, but I can predict how things will work with them. For my game, 5089, I offer different movement modes. I allow the camera to be turned in some modes because I expect some players (and developers) may target mouse & keyboard or controller support, where they will need to turn with something other than their body. Restricting features to a fixed camera rotation is restricting this toolkit to only 360 degree Vive room scale support, which is a rather limited subset of SteamVR.

**Comment by thestonefox** [comment]
I may see if I can compensate for the rotation with the beams. It should be doable I think

**Comment by phr00t** [comment]
Thank you. It should be a case of making everything relative to the camera rig's rotation, and not the absolute rotation of the tracked objects.

**Comment by RoccoGD** [comment]
Here is a game with a very smart use of grid rotating before teleporting.

At 3:10 -> https://www.kickstarter.com/projects/708582338/dimensional-a-ground-breaking-vr-only-experience/description

**Comment by thestonefox** [comment]
@RoccoGD thats a really neat idea I like that a lot!

**Comment by thestonefox** [comment]
Fixed with commit 27c07f6da240b4bcec10e1eb7336edbec1ec8d03

Stupidly easy fix! That's what happens when you don't review code you wrote at the start :)

Hopefully this works much better for people now. The camera rig can be rotated to any angle and even in real time it shouldn't affect the beam direction.
