### ISSUE TITLE
Touchpad walking only when touchpad is pressed.

### ISSUE THREAD

**Issue by Code47X** [thestonefox/SteamVR_Unity_Toolkit#558]
With the current touchpad movement script locomotion starts as soon as the touchpad is touched. I was wondering if there is a way to have the same functionality but only have the locomotion start if the touchpad is actually pressed down.  Just looking for a little insight on how I could modify the script(s) to act in this way.

If this is something easy to implement I think a variable visible in the inspector to toggle touch/press touchpad locomotion would be a great addition.

**Comment by Code47X** [comment]
So I actually just added a listener in the

**Comment by thestonefox** [comment]
Since this commit -> https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/6fa5d5bfb89d69cc7ec01aea532b78871d3d8c58

You can now specify a button to press before the touchpad walking is activated.

e.g. you press the trigger then the touchpad will activate your walk as you move over it.

But you can also set the button to activate as "Touchpad Press" which would give you what you wanted.

I.e. you press the touchpad (to activate walking) then moving your finger across the touchpad would move you.

**Comment by Code47X** [comment]
Yup I was working off an older version of your toolkit, noticed it shortly after I posted. Thank you for the response, you're doing great work man. Hoping I can contribute at some point!
