### ISSUE TITLE
Highlighting with Simple Pointer

### ISSUE THREAD

**Issue by williamedwardhahn** [thestonefox/SteamVR_Unity_Toolkit#597]
Is there a way to use the simple pointer to highlight interactable objects? The examples only contain ways to highlight an object upon touching the object.

**Comment by thestonefox** [comment]
At the moment no, but I'll look into using pointers as something that can "Touch" interactable objects, you can already "Use" interactable objects with a pointer.

**Comment by getwilde** [comment]
This would be a nice enhancement; essentially starting the blur the lines between "touching" larger objects with your controller, and smaller objects with a (precision) laser pointer.  It could be taken a step further to allow _grabbing_ an object with a laser pointer as well  (using is already possible.)

**Comment by thestonefox** [comment]
yeah @getwilde I'm thinking of making the pointers work like a controller.

so a pointer would be able to touch/grab/use interactable objects.

**Comment by getwilde** [comment]
Nice! Sounds good.

**Comment by thestonefox** [comment]
Ok so I have a PR that should address this: 
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/614

It basically allows the pointer to be an extension of the controller, so when the pointer touches an item it's like the controller is touching it too.

**Comment by pixelvspixel** [comment]
Love the new update, I think it could be worthwhile to have a the ability to toggle grabbing as it currently works by pulling the selected item back to you, along with being able to maintain a grabbed objects current distance during manipulation.

This seems to be a common mechanic in VR. I think it'd be useful in tweaking objects slightly from a distance without completely resetting their placement and rotation and also useful for people dealing with miniatures.

**Comment by thestonefox** [comment]
@pixelvspixel yeah this is something i'm considering.

I actually did play with it, where the attach point went at the end of the pointer beam. But there were a number of issues with it.

Like you don't know if it's the pointer or the controller that's actually doing the colliding (because compound trigger colliders don't report the actual collider in the collision).

also what should happen to the pointer length when you've grabbed something? In my quick test, the pointer length was still affected by what you pointed at so would shoot your object into the distance.

My one thought here would be the pointer length is maxed at the length of the grab perhaps.

**Comment by getwilde** [comment]
> Like you don't know if it's the pointer or the controller that's actually doing the colliding (because compound trigger colliders don't report the actual collider in the collision).
I won't pretend to understand (or know how to solve) whatever challenges you were running into, but I _can_ say that I recently learned about RaycastHit.collider. :)  Would that help?
