### ISSUE TITLE
Implement Y movement for TouchpadWalking

### ISSUE THREAD

**Issue by robmerki** [thestonefox/SteamVR_Unity_Toolkit#636]
The [VRTK_TouchpadWalking.cs](https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/VRTK/Scripts/VRTK_TouchpadWalking.cs) script does not allow us to traverse the Y axis, due to `float fixY = transform.position.y`. This means that players fall through the game level (or fly) while traversing hills, slopes, etc.

Relevant code here:

```csharp
        public void Move()
        {
            var deviceDirector = VRTK_DeviceFinder.DeviceTransform(deviceForDirection);
            var movement = deviceDirector.forward * movementSpeed * Time.deltaTime;
            var strafe = deviceDirector.right * strafeSpeed * Time.deltaTime;
            float fixY = transform.position.y;
            transform.position += (movement + strafe);
            transform.position = new Vector3(transform.position.x, fixY, transform.position.z);
        }
```

**Comment by thestonefox** [comment]
If you apply the Player Presence script to your camera rig, it will add a collider and rigidbody that will allow the touchpad walking to traverse Y correctly.

Check out the example scene to see this working.

**Comment by robmerki** [comment]
Wow that was super easy. Works perfectly. Thanks!

**Comment by sisse008** [comment]
Hi, I dont see that this script is available anymore and I am having the same issue. was the class name changed?

Thank you,
Danielle

**Comment by thestonefox** [comment]
Look at example scene 17, it will have the new scripts required to do touchpad walking

**Comment by sisse008** [comment]
thank you for the quick response. I am referring to the issue robmerki  was having, which im now having too. in example scene 17, if I would add a cube collider on either sides of a ground with a slope (like the blue hill in the example scene), than i would not collide with that collider while walking up/down the slope (i would instead walk through the cube, as if it does not have a collider). 
this is a problem in my game because the player can walk through walls when walking up the stairs (stairs is just a tilted plane).
if i understood correctly, the Player Presence script was suppose to fix this, but it is no longer available. 

Thank you,
Danielle

**Comment by thestonefox** [comment]
the script is called VRTK_BodyPhysics now

**Comment by sisse008** [comment]
in example scene 17, the script VRTK_BodyPhysics is attached to the PlayArea. but still, when walking up/down a tilting plane (like the blue hill in the example scene), side colliders (like wallks on either side if the hill) are ignored.

**Comment by thestonefox** [comment]
That's a separate issue: 
https://github.com/thestonefox/VRTK/issues/746

**Comment by sisse008** [comment]
it is not similar to my issue. my issue is that my playArea is walking right through vertical gameobjects with colliders (like a wall). but, this only happens while the playArea is moving up (or down) a plain which is tilted (like the blue hill in example 17).
I will make a video and share the link to try and show the problem.

thank you
