### ISSUE TITLE
[Issue] Teleporting near another object e.g. a wall with a ledge on top causes you to teleport ontop of it

### ISSUE THREAD

**Issue by xx1guardian1xx** [thestonefox/SteamVR_Unity_Toolkit#78]
When you teleport directly next to a wall or any 3d object it will likely place you ontop of said wall even though the pointer was hitting the ground next to the wall

**Comment by thestonefox** [comment]
That's being caused by the play space falling option on the teleport script.

It basically sends a ray down from the headset to know where the nearest floor is. This means if you walk off a ledge you fall down, or if you walk up stairs then it does that too.

You can turn it off to prevent your issue.

Alternatively update the script to not have the ray collision work with certain objects (e.g with tags)

**Comment by xx1guardian1xx** [comment]
I think I've modified mine too much and buggered it up because it does it regardless of if play space falling is on

**Comment by thestonefox** [comment]
Look for the fall to play space method in the height adjust teleporter. You can check the collided object there to prevent it falling. If you get stuck let me know I'll find the code and show you what I mean

**Comment by xx1guardian1xx** [comment]
Yeah I've defiently buggered it up, I seem to randomly reset to the spawn position now every so often.
What part of code should I modify?

**Comment by thestonefox** [comment]
On line 70 of the HeightAdjust Teleport

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_HeightAdjustTeleport.cs#L70

is where the drop to floor bit runs.

Then on line 78

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_HeightAdjustTeleport.cs#L78

Is the bit that determines whether the drop to floor should work, so that if statement needs updating.

it currently looks like this

`if (rayHit && ! FloorIsGrabbedObject(rayCollidedWith) && ( MeshYChanged(rayCollidedWith, floorY) || CurrentFloorChanged(rayCollidedWith) ) )`

You want to do a check there on the rayCollidedWith object maybe check for a tag on it, like so:

`if (rayHit && rayCollidedWith.gameObject.tag != "yourtaghere" && !FloorIsGrabbedObject(rayCollidedWith) && ( MeshYChanged(rayCollidedWith, floorY) || CurrentFloorChanged(rayCollidedWith) ) )`

I added this condition `rayCollidedWith.gameObject.tag != "yourtaghere"`


Hope that helps

**Comment by xx1guardian1xx** [comment]
I've reset all my scripts to your latest ones and tried this, except now I phsyically can't teleport anywhere. I'll try to resolve this myself. The rayCollidedWith.gameObject.tag  needed to be rayCollidedWith.transform.gameObject.tag to work but other than that no errors. I'll see it works once I figure out this teleport issue

**Comment by xx1guardian1xx** [comment]
No luck fixing the teleport, although I am gettign this error on the default scripts,
https://gyazo.com/e48fbda92e2c202cc1c533a191d4d380
Another idea for limiting movement is maybe you could bake a navigation mesh and have an option for the play only to be able to travel in the nav meshes zones?

**Comment by thestonefox** [comment]
Ah ok that error is because you don't have a pointer attached to your controllers but you're trying to use the teleporter script.

If you put the simple pointer or bezier pointer script on your controller objects then the teleporter script will be able to listen to the events correctly. Without that script then the teleport could never work.

Navigation meshes are a potential solution, they're a bit more advanced though and users would have to generate their own. It's something to consider though

**Comment by xx1guardian1xx** [comment]
Err, I certianly have a pointer attached. Still getting the error :/
https://gyazo.com/8ffdc7d0d31086a7cb3b5e470ac652c4

**Comment by thestonefox** [comment]
Is your controller turned on and showing up as Green in SteamVR?

That error is because it can't find a controller with the WorldPointer script on it (or any child of WorldPointer like SimplePointer or BezierPointer).

This happens if the controller isn't switched on because the script doesn't register.

**Comment by xx1guardian1xx** [comment]
Fixed it, it's because I modifiy line 145 of world pointer because I need to know the name of my controller in my scripts and world pointer changes it which is a bit of hassle.

The modification you suggested to line 78 of height adjust basically just stops it from falling on my version. Is that the location I should do a check if I want to teleport only to certian tags?

**Comment by thestonefox** [comment]
If you need to still check for the name of the controller instead of doing name == "<controller name>"

you can check to see if it contains that name e.g. name.Contains("<controller name>") then it will just to a partial match so should still work for you.

And for the teleport to certain tags, you don't want to do it there, you want to do it in the "DoTeleport()" method in the BasicTeleporter script.

**Comment by xx1guardian1xx** [comment]
I'm not too sure what I should modifiy to check for the terrain tags in the doteleport method, would it be e.target?

**Comment by thestonefox** [comment]
yeah e.target is the thing that is your teleport location.

so you can check to see if e.target.gameObject.tag is equal to something and if it is then just return or don't do the rest of the teleport script.

**Comment by xx1guardian1xx** [comment]
Alright, also I found out that if you have the teleport script set on the lefthand and your controller isn't in tracking range, it basically turns the controller off inside of unity meaning that it can't find the pointer which is why I got that error as my pointer is on the left controller

**Comment by thestonefox** [comment]
Rolling this up into a new issue:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/105
