### ISSUE TITLE
Says 'A GameObject must exist with a SteamVR_WorldPointer script'

### ISSUE THREAD

**Issue by SilverRin** [thestonefox/SteamVR_Unity_Toolkit#86]
This might be something simple, but it's been driving me crazy. There are often times when running the simple teleport script that I get this error and I can't use the controllers to teleport. This includes running your examples (For instance 004_CameraRig_BasicTeleport). What's maddening is that other times the script runs fine. 

I've tried re-adding the script to your CameraRig, but then it says  'Can't add script behaviour Steam_VR_WorldPointer. The script class can't be abstract!'

I have got a build to work by rebooting, but then after awhile it'll toss that error again. Any ideas?

**Comment by thestonefox** [comment]
The error is because your controller isn't being registered with SteamVR at the point you run your scene so when the teleport script looks for a WorldPointer it cannot find one (because they're attached to the controller).

The solution is to just make sure your controllers are not flashing green on SteamVR and can be seen by the base station (so they're registered).

The WorldPointer is abstract, but the SimplePointer and BezierPointer are both concrete implementations of the WorldPointer.

So in essence the message is just saying you don't have (or it can't find) a SimplePointer or BezierPointer attached to any controllers.

**Comment by SilverRin** [comment]
Ah, thanks! That's it. I don't suppose there's some sort of command to wake up controllers? Or maybe a way to not run the script unless the controllers are found. That way if you turn them on after the program is running, the teleport will work instead of having given up.

**Comment by thestonefox** [comment]
There's no way I know of waking up the controllers via the Unity plugin. That's something the core SteamVR system would do.

If the script doesn't fail if it can't find the controllers then the teleporter would never work (because it needs a controller to work).

If you turn on a controller after you've started the scene running there is no way of guaranteeing that Unity will recognise the controller (again out of my control unfortunately)

**Comment by SilverRin** [comment]
Got it. Thanks for all the help, by the way, I really appreciate it.

**Comment by SilverRin** [comment]
Ah, just figured out a way to make this work...in theory. I made a scene with a teleport scene and ran it with the 'Steam VR_Basic Teleport' and the 'Steam VR_Simple Pointer' script checked off...and with both controllers off. Then, I ran the scene, and no error was caused. Then, while the program was running I turned on the controllers and I clicked the scripts on. There was no error and the teleport script worked fine.

Now, in theory, all I have to do is have some script that checks to see if a controller is detected. If so, it enables the two teleport scripts. Do you know of a way of doing that? If not I'll look into it.

**Comment by thestonefox** [comment]
There is a steamVr script called controller manager. Not sure if that has a way to detect the controller status. Worth looking into

**Comment by SilverRin** [comment]
Can't figure it out right now since I'm a bit out of my depth. I'll probably try to turn on a HUD message with the teleporter script that at least warns the user to turn on the controller and restart the game (putting it where the console warning is right now). Otherwise they could be playing the game and everything works fine but the teleporter and they wouldn't know why.

**Comment by thestonefox** [comment]
I'll try take a look in a bit if i can :)

**Comment by SilverRin** [comment]
Thanks, I really appreciate it!

**Comment by thestonefox** [comment]
I have a semi fix for this to prevent it from failing with an error, but I'm going to investigate further, because it still disables the second connected pad if it cant find it in time. 

going to see if there's an event emitted that I can use to listen in on

**Comment by thestonefox** [comment]
think i may have fixed it

**Comment by thestonefox** [comment]
fixed with commit c13d6e3176fad5d4d39cd2f8a9c4f3cbc35d93e4
