### ISSUE TITLE
[Suggestion] Align custom object along curved beam?

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [thestonefox/SteamVR_Unity_Toolkit#88]
The new custom beam object feature is great since you can reduce polycount by a decent amount with the right object. Unfortunately, the lowest poly object I can think of, a simple arrow(2 tris), doesn't work as well as I hoped since it doesn't align along the beam curve.

Is it possible to have it align along the curve? Even as just a toggle.

**Comment by thestonefox** [comment]
The bezier pointer isn't really geared towards the effect you're trying to achieve.

All it does is plots game objects at set points along the curve.

To get something to bend across a curve you need to bend each 3d object along it's vertices within the curve, but none of the Unity primitives (as far as I know) have side vertices

For instance, you can bend a cylinder in many 3d packages (blender, 3dmax, etc) because they are made up of segments (i.e. many side vertices).

Problem with this is I want the bezier pointer to work with unity primitives because I don't want dependencies on other graphics packages (as people may not have them). It would also be very difficult to build something that matched many common solutions.

The other solution to drawing a curved line (e.g. like the one in The Lab) is to not use primitives plotted across a curve, but to draw a mesh with the mesh renderer. But this is a different thing all together.

I think the best solution would be to offer a different Pointer script that generated a parabolic curve with a mesh to suit these needs.

**Comment by mimminito** [comment]
What about just the ability to align the objects along the curve, not to bend? So at each point, it has a rotation value based on its position on the curve, and that is used to angle the object thats being displayed. No idea how to do it, but that would work :)

**Comment by thestonefox** [comment]
@mimminito That's a good idea, I'll implement that now, I think it will work well!

**Comment by frozenMeatpopsicle** [comment]
Ah, yes, that's what I meant. Sorry if that was unclear.

**Comment by thestonefox** [comment]
@frozenMeatpopsicle no worries it's a good idea, just implemented it, looks great. I'll be pushing it soon

**Comment by thestonefox** [comment]
Try the latest commit:
b47f2c6b8ae6cc02cc054ea828f1e8209d5c9522

Let me know what you think. If it's good I'll close this.

**Comment by frozenMeatpopsicle** [comment]
Looks good. Thanks for the quick work!

**Comment by thestonefox** [comment]
@frozenMeatpopsicle thanks for checking it out and the ideas :)

**Comment by mimminito** [comment]
Looks good to me :)
